name: Eleventy Build

on:
  push:
    branches:
      - source
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        env:
          GA_API_ENDPOINT: ${{ secrets.GA_API_ENDPOINT }}
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
